# Generated by Django 5.0.6 on 2024-07-19 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=20)),
                ('e_dob', models.DateField()),
                ('e_salary', models.IntegerField()),
                ('e_daily_work_hours', models.IntegerField()),
                ('e_weekend_day', models.IntegerField()),
                ('e_contact', models.CharField(max_length=10)),
                ('e_email', models.CharField(max_length=50)),
                ('e_password', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
        migrations.CreateModel(
            name='subscription_details',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_max_problem_solve_qty', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'subscription_details',
            },
        ),
        migrations.CreateModel(
            name='feedback_details',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_description', models.CharField(max_length=100)),
                ('f_date', models.DateField()),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.employee_details')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
        migrations.CreateModel(
            name='problem_details',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_description', models.CharField(max_length=100)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.employee_details')),
            ],
            options={
                'db_table': 'problem_details',
            },
        ),
        migrations.CreateModel(
            name='improvement_details',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_theme', models.CharField(max_length=100)),
                ('i_objective_key_results', models.CharField(max_length=200)),
                ('generated_date', models.DateField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.problem_details')),
            ],
            options={
                'db_table': 'improvement_details',
            },
        ),
        migrations.AddField(
            model_name='employee_details',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.subscription_details'),
        ),
    ]
